// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGgQM5GTbyvubvNhwgHreFYOcVEeK23OE',
    appId: '1:341845157877:web:1b2711ae168c88855962bc',
    messagingSenderId: '341845157877',
    projectId: 'workoutapp-ai-integration',
    authDomain: 'workoutapp-ai-integration.firebaseapp.com',
    storageBucket: 'workoutapp-ai-integration.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqWvAq2xjaJEVRXfSytY_f6ZoBOCFk_Y',
    appId: '1:341845157877:android:d69ac2dca26115705962bc',
    messagingSenderId: '341845157877',
    projectId: 'workoutapp-ai-integration',
    storageBucket: 'workoutapp-ai-integration.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfL1quGWzPBRGBkGe0h32pAUWMiOq_vqU',
    appId: '1:341845157877:ios:8d60acb53420e51a5962bc',
    messagingSenderId: '341845157877',
    projectId: 'workoutapp-ai-integration',
    storageBucket: 'workoutapp-ai-integration.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfL1quGWzPBRGBkGe0h32pAUWMiOq_vqU',
    appId: '1:341845157877:ios:8d60acb53420e51a5962bc',
    messagingSenderId: '341845157877',
    projectId: 'workoutapp-ai-integration',
    storageBucket: 'workoutapp-ai-integration.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGgQM5GTbyvubvNhwgHreFYOcVEeK23OE',
    appId: '1:341845157877:web:4a0312a1902e8aa65962bc',
    messagingSenderId: '341845157877',
    projectId: 'workoutapp-ai-integration',
    authDomain: 'workoutapp-ai-integration.firebaseapp.com',
    storageBucket: 'workoutapp-ai-integration.firebasestorage.app',
  );
}
